# Generated by Django 3.1.3 on 2020-12-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('movie_ids', models.CharField(max_length=50)),
                ('pic', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('movie_ids', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('budget', models.PositiveIntegerField()),
                ('genres', models.TextField()),
                ('language', models.CharField(max_length=2)),
                ('overview', models.TextField()),
                ('companies', models.TextField()),
                ('countries', models.TextField()),
                ('release_date', models.DateField()),
                ('revenue', models.PositiveIntegerField()),
                ('runtime', models.FloatField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.PositiveIntegerField()),
                ('poster', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=70)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('movie_ids', models.CharField(max_length=50)),
            ],
        ),
    ]
