# Generated by Django 3.1.3 on 2020-12-03 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201203_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
