# Generated by Django 3.1.3 on 2020-12-07 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20201203_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='movie_ids',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='director',
            name='movie_ids',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='writer',
            name='movie_ids',
            field=models.TextField(),
        ),
    ]
